### ISSUE TITLE
Why i can't use the involution directly?

### ISSUE THREAD

**Issue by Panghu-coder** [d-li14/involution#11]
i just wanna use the involution as a plugins module for test. 
Here's my code.

import sys
sys.path.append('..')
import torch.nn as nn
import torch
from utils.involution_cuda import involution

class test(nn.Module):
    def __init__(self):
        super(test,self).__init__()
        self.conv = involution(channels=3,kernel_size=3,stride=1)
    def forward(self,x):
        out = self.conv(x)
        return out

model = test()
model.cuda()
x = torch.ones(1,3,224,224).cuda()
print(x)
out = model(x)
print(out)

but I got the false as following:
Traceback (most recent call last):
  File "/home/panghu/anaconda3/envs/torchTAP/involution/cls/mmcls/models/backbones/test.py", line 24, in <module>
    model = A()
  File "/home/panghu/anaconda3/envs/torchTAP/involution/cls/mmcls/models/backbones/test.py", line 19, in __init__
    self.conv = involution(channels=3,kernel_size=3,stride=1)
  File "../utils/involution_cuda.py", line 265, in __init__
    act_cfg=dict(type='ReLU'))
  File "/home/panghu/anaconda3/envs/torchTAP/lib/python3.6/site-packages/mmcv/cnn/bricks/conv_module.py", line 125, in __init__
    bias=bias)
  File "/home/panghu/anaconda3/envs/torchTAP/lib/python3.6/site-packages/mmcv/cnn/bricks/conv.py", line 41, in build_conv_layer
    layer = conv_layer(*args, **kwargs, **cfg_)
  File "/home/panghu/anaconda3/envs/torchTAP/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 332, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/home/panghu/anaconda3/envs/torchTAP/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 46, in __init__
    self.reset_parameters()
  File "/home/panghu/anaconda3/envs/torchTAP/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 49, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/panghu/anaconda3/envs/torchTAP/lib/python3.6/site-packages/torch/nn/init.py", line 310, in kaiming_uniform_
    fan = _calculate_correct_fan(tensor, mode)
  File "/home/panghu/anaconda3/envs/torchTAP/lib/python3.6/site-packages/torch/nn/init.py", line 279, in _calculate_correct_fan
    fan_in, fan_out = _calculate_fan_in_and_fan_out(tensor)
  File "/home/panghu/anaconda3/envs/torchTAP/lib/python3.6/site-packages/torch/nn/init.py", line 211, in _calculate_fan_in_and_fan_out
    receptive_field_size = tensor[0][0].numel()
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by Panghu-coder** [comment]
I'm so sorry. I have set the error channels and reduction ration so that i made the outputchannel=0

**Comment by Huuush** [comment]
Sry to bother. I also want to insert involution block to my network. How did you deal with it? Did it mean that I need to train from scratch without pre-train model?
