### ISSUE TITLE
What version of mmdet does det support?

### ISSUE THREAD

**Issue by ma3252788** [d-li14/involution#5]
I use mmdet2.7, but it doesn't work.

```

Traceback (most recent call last):
  File "/home/ubuntu/bigdisk/part1/mmdet2/tools/train.py", line 185, in <module>
    main()
  File "/home/ubuntu/bigdisk/part1/mmdet2/tools/train.py", line 159, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/mmcv/utils/config.py", line 363, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/mmcv/utils/config.py", line 43, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'train_cfg'
```

**Comment by yanlongbinluck** [comment]
Hi, I have the same error.
Have you solved it? Which version of mmdet do you use finally?
Thank you!
