### ISSUE TITLE
No module named 'mmdet.models.dense_heads.rpn_test_mixin'

### ISSUE THREAD

**Issue by Xbox-9527** [d-li14/involution#53]
Just like the title,when I used mmdetecion to run this " python demo/image_demo.py".

I got the error report, as follows:

Please run python mmdet/utils/collect_env.py to collect necessary environment information and paste it here.

TorchVision: 0.6.0+cu101
OpenCV: 4.5.4-dev
MMCV: 1.3.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.18.0+

How you installed PyTorch [e.g., pip, conda, source]
from source

Error traceback
Traceback (most recent call last):
File "demo/image_demo.py", line 5, in
from mmdet.apis import (async_inference_detector, inference_detector,
File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/apis/init.py", line 2, in
from .inference import (async_inference_detector, inference_detector,
File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/apis/inference.py", line 12, in
from mmdet.datasets import replace_ImageToTensor
File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/datasets/init.py", line 12, in
from .utils import (NumClassCheckHook, get_loading_pipeline,
File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/datasets/utils.py", line 9, in
from mmdet.models.dense_heads import GARPNHead, RPNHead, RPNHead_involution
File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/models/init.py", line 7, in
from .dense_heads import * # noqa: F401,F403
File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/models/dense_heads/init.py", line 24, in
from .rpn_head_involution import RPNHead_involution
File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/models/dense_heads/rpn_head_involution.py", line 13, in
from .rpn_test_mixin import RPNTestMixin
ModuleNotFoundError: No module named 'mmdet.models.dense_heads.rpn_test_mixin'

**Comment by Xbox-9527** [comment]
I commented out them in the every init.py ,so I can use it now.
Maybe there lacks some files
