### ISSUE TITLE
CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES: too many resources requested for launch

### ISSUE THREAD

**Issue by ma3252788** [d-li14/involution#6]
After I fixed the last problem, I encountered this problem:

```
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = '/home/ubuntu/mmdet2.x_model/faster_rcnn_red50_neck_fpn_1x_voc_SIXray'
gpu_ids = range(0, 1)

2021-03-17 16:17:23,116 - mmdet - INFO - Start running, host: ubuntu@mcj, work_dir: /home/ubuntu/mmdet2.x_model/faster_rcnn_red50_neck_fpn_1x_voc_SIXray
2021-03-17 16:17:23,117 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "/home/ubuntu/bigdisk/part1/mmdet2/tools/train.py", line 185, in <module>
    main()
  File "/home/ubuntu/bigdisk/part1/mmdet2/tools/train.py", line 181, in main
    meta=meta)
  File "/home/ubuntu/bigdisk/part1/mmdet2/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ubuntu/bigdisk/part1/mmdet2/mmdet/models/detectors/base.py", line 246, in train_step
    losses = self(**data)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/bigdisk/part1/mmdet2/mmdet/models/detectors/base.py", line 180, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/ubuntu/bigdisk/part1/mmdet2/mmdet/models/detectors/two_stage.py", line 142, in forward_train
    x = self.extract_feat(img)
  File "/home/ubuntu/bigdisk/part1/mmdet2/mmdet/models/detectors/two_stage.py", line 82, in extract_feat
    x = self.backbone(img)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/bigdisk/part1/mmdet2/mmdet/models/backbones/rednet.py", line 592, in forward
    x = self.stem(x)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/mmdet2.x/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/bigdisk/part1/mmdet2/mmdet/models/utils/involution_cuda.py", line 278, in forward
    out = _involution_cuda(x, weight, stride=self.stride, padding=(self.kernel_size-1)//2)
  File "/home/ubuntu/bigdisk/part1/mmdet2/mmdet/models/utils/involution_cuda.py", line 235, in _involution_cuda
    out = _involution.apply(input, weight, _pair(stride), _pair(padding), _pair(dilation))
  File "/home/ubuntu/bigdisk/part1/mmdet2/mmdet/models/utils/involution_cuda.py", line 171, in forward
    stream=Stream(ptr=torch.cuda.current_stream().cuda_stream))
  File "cupy/cuda/function.pyx", line 182, in cupy.cuda.function.Function.__call__
  File "cupy/cuda/function.pyx", line 164, in cupy.cuda.function._launch
  File "cupy_backends/cuda/api/driver.pyx", line 299, in cupy_backends.cuda.api.driver.launchKernel
  File "cupy_backends/cuda/api/driver.pyx", line 124, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES: too many resources requested for launch
```

**Comment by d-li14** [comment]
Given the current information, possibly the GPU memory is not enough.

**Comment by ma3252788** [comment]
> Given the current information, possibly the GPU memory is not enough.

Thanks for the reply, the GPU I am using is GTX2080 Ti, and all other programs are no problem. Can I not use cupy?

**Comment by d-li14** [comment]
Could you please provide more information? For example, input size, batch size per GPU.
Alternatively, you could definitely use a pure PyTorch version with `involution_naive.py`, which is easier to debug but more memory-consuming. In addition, when memory is the bottleneck, one workaround is to add `--with-cp=True` to the running command to use checkpointing. Refer to MMDet for more details about this.

**Comment by cl886699** [comment]
i got the same error, did you resolve this

**Comment by aiyodiulehuner** [comment]
i got the same error, did you resolve this

**Comment by Doubiiu** [comment]
I think this error should be caused by OOM in GPU.

**Comment by RokiaAbdeen** [comment]
I got the same error , anyone solved it ??

**Comment by shangshang0912** [comment]
您的邮件已经收到。我会及时做出回复。
